version: "3"
services: 
  db:
    image: postgres
    env_file:
      - ./db.env
    volumes: 
      - ./db/data:/var/lib/postgreql/data
    ports:
      - "5432:5432"
  
  server:
    image: astorgato/prueba-backend:latest
    env_file:
      - ./app.env
    depends_on:
      - db
    ports:
      - "4999:4999"
